[general]
import = [
  "catppuccin-latte.toml",
]
working_directory = "E:/"

[font]
size = 10
normal = { family = "Maple Mono NF CN", style = "Regular" }
bold = { family = "Maple Mono NF CN", style = "Bold" }
italic = { family = "Maple Mono NF CN", style = "Italic" }
bold_italic = { family = "Maple Mono NF CN", style = "Bold Italic" }

[cursor]
style = { shape = "Beam", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Always" }
unfocused_hollow = true

[terminal]
shell = "C:/Users/RicardoRyn/scoop/apps/nu/current/nu.exe"

[selection]
save_to_clipboard = true

