#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Ricardo"
email = "ricardoryn1317@gmail.com"

[lazyjj]
highlight-color = "#cccccc"

[ui]
editor = "nvim"
paginate = "auto"
default-command = "log"

[git]
private-commits = '''description(glob:'WIP:*')''' # 以“WIP:”开头的为私有提交
