"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Ricardo_T8"
email = "ricardoryn1317@gmail.com"

[ui]
default-command = "log"
editor = "nvim"
pager = ["delta", "--pager", "less -FRX"]
diff-formatter = ":git"

[git]
private-commits = '''description(glob:'WIP:*')'''

[lazyjj]
highlight-color = "#cccccc"
diff-tool = "delta"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"
