color0 #f7f9ff
color1 #ba1a1a
color2 #68587a
color3 #51606f
color4 #2f628c
color5 #d3bfe6
color6 #b9c8da
color7 #181c20
color8 #72777f
color9 #ba1a1a
color10 #68587a
color11 #51606f
color12 #2f628c
color13 #d3bfe6
color14 #b9c8da
color15 #181c20

cursor                #181c20
cursor_text_color     #f7f9ff
background            #f7f9ff
foreground            #181c20
selection_foreground  #42474e
selection_background  #dee3eb
url_color             #2f628c