color0 #f7f9ff
color1 #ba1a1a
color2 #7f4297
color3 #43617d
color4 #006097
color5 #ecb1ff
color6 #abcaea
color7 #181c20
color8 #707882
color9 #ba1a1a
color10 #7f4297
color11 #43617d
color12 #006097
color13 #ecb1ff
color14 #abcaea
color15 #181c20

cursor                #181c20
cursor_text_color     #f7f9ff
background            #f7f9ff
foreground            #181c20
selection_foreground  #404850
selection_background  #dbe3ee
url_color             #006097