[[mgr.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[mgr.prepend_keymap]]
on   = "2"
run  = "plugin smart-switch 1"
desc = "Switch or create tab 2"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "q"
run  = "plugin confirm-quit"
desc = ""

[[mgr.prepend_keymap]]
on   = "<C-f>"
run  = "seek 5"

[[mgr.prepend_keymap]]
on   = "<C-b>"
run  = "seek -5"
