"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
dark  = ""
light = ""

[icon]
dirs  = [
  { name = ".config", text = "" },
  { name = ".git", text = "" },
  { name = ".github", text = "" },
  { name = ".npm", text = "" },
  { name = "Desktop", text = "" },
  { name = "Development", text = "" },
  { name = "Documents", text = "" },
  { name = "Downloads", text = "" },
  { name = "Library", text = "" },
  { name = "Movies", text = "" },
  { name = "Music", text = "" },
  { name = "Pictures", text = "" },
  { name = "Public", text = "" },
  { name = "Videos", text = "" },
  # 自定义
  { name = "Ricardo", text = "" },
  { name = "ricardo", text = "" },
  { name = "python", text = "" },
  { name = "rust", text = "" },
  { name = "lua", text = "" },
]
