watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 24
    padding:
      top: 7
      left: 8
      bottom: 0
      right: 8
    widgets:
      left:
        [
          "glazewm_tiling_direction",
          "glazewm_workspaces",
          "bin",
          "github",
          "copilot",
          "todo",
          "active_window",
        ]
      center: ["clock"]
      right: ["volume", "bluetooth", "wifi", "systray", "power_menu"]
widgets:
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
    blur_effect:
      enabled: true # 开启模糊效果
      acrylic: true # 启用 Windows 10 的 Acrylic 模糊（若使用 Windows 11 则自动启用更高级效果）
      dark_mode: true # 深色主题模式下增强阴影
      round_corners: false # 是否使用圆角（可选）
      round_corners_type: "normal"
      border_color: None # 可配置边框颜色（如 “System” 或 HEX 值）
  bin:
    type: "yasb.recycle_bin.RecycleBinWidget"
    options:
      label: "<span>{icon}</span> {items_count}"
      label_alt: "Items {items_count}, Total size ({items_size})"
      icons:
        bin_empty: "\udb82\ude7a"
        bin_filled: "\udb82\ude79"
      callbacks:
        on_left: "open_bin"
        on_right: "toggle_label"
        on_middle: "empty_bin"
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}" # {data} return number of unread notification
      token: env # GitHub Personal access tokens (classic) https://github.com/settings/tokens
      max_notification: 30 # Max number of notification displaying in menu max: 50
      notification_dot:
        enabled: True
        corner: "bottom_left" # Can be "top_left", "top_right", "bottom_left", "bottom_right"
        color: "red" # Can be hex color or string
        margin: [1, 1] # x and y margin for the dot
      only_unread: false # Show only unread or all notifications;
      show_comment_count: false # Summarize comment totals for issues, PRs, and discussions
      reason_filters: [] # e.g. ['mention', 'assign'] to limit notifications by reason
      max_field_size: 54 # Max characters in title before truncation.
      update_interval: 300 # Check for new notification in seconds
      menu:
        blur: True # Enable blur effect for the menu
        round_corners: True # Enable round corners for the menu (this option is not supported on Windows 10)
        round_corners_type: "normal" # Set the type of round corners for the menu (normal, small) (this option is not supported on Windows 10)
        border_color: "System" # Set the border color for the menu (this option is not supported on Windows 10)
        alignment: "left"
        direction: "down"
        show_categories: false
        categories_order:
          ["PullRequest", "Issue", "CheckSuite", "Release", "Discussion"]
      label_shadow:
        enabled: False
        color: "black"
        radius: 3
        offset: [1, 1]
  copilot:
    type: "yasb.copilot.CopilotWidget"
    options:
      label: "{icon} {used}/{allowance}"
      label_alt: "<span>{icon}</span>"
      token: env
      plan: "pro" #Set your plan "pro" or "pro_plus"
      tooltip: true
      update_interval: 120
      icons:
        copilot: ""
        error: ""
      thresholds:
        warning: 75
        critical: 90
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
        chart: true
      animation:
        enabled: true
        type: "fadeInOut"
        duration: 200
  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "\uf0ae {count}/{completed}"
      label_alt: "\uf0ae Tasks: {count}"
      # data_path: "~/Documents/my-todos.json"  # Optional: custom JSON file path
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
      icons:
        add: "\uf501 New Task"
        edit: "Edit"
        delete: "Delete"
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "General"
        soon:
          label: "Complete soon"
        today:
          label: "End of day"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 36
      max_length_ellipsis: "..."
      monitor_exclusive: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %b %d %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
      calendar:
        alignment: "center"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span> {device_count}"
      label_alt: "{device_name}"
      label_no_device: "No devices connected"
      label_device_separator: ", "
      max_length: 10
      max_length_ellipsis: "..."
      icons:
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      device_aliases:
        - name: "T5.0"
          alias: "\uf025"
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "\ueba9"
      get_exact_wifi_strength: false # Optional. Will require location access permission if true.
      wifi_icons: [
          "\udb82\udd2e", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-24% strength
          "\udb82\udd22", # Icon for 25-49% strength
          "\udb82\udd25", # Icon for 50-74% strength
          "\udb82\udd28", # Icon for 75-100% strength
        ]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: ["\ue670", "\ue671", "\ue672", "\ue673"]
        wifi_icons_unsecured: ["\uec3c", "\uec3d", "\uec3e", "\uec3f"]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "▼"
      label_expanded: "▶"
      label_position: "left" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250 # Milisecond
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        lock: ["\uea75", "Lock"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["\udb81\udf3a", "Cancel"]
