#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[revset-aliases]
"trunk()" = "main@origin"

[fix.tools.1-stylua]
command = ["stylua", "--stdin-filepath=$path", "-"]
patterns = ["glob:'**/*.lua'", "glob:'**/*.luau'"]
