[[mgr.prepend_keymap]]
on   = "<C-u>"
run  = "arrow -5"
desc = "Move cursor up 5 items"

[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "arrow 5"
desc = "Move cursor down 5 items"

[[mgr.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[mgr.prepend_keymap]]
on   = "2"
run  = "plugin smart-switch 1"
desc = "Switch or create tab 2"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "q"
run  = "plugin confirm-quit"
desc = ""

[[mgr.prepend_keymap]]
on   = "<C-f>"
run  = "seek 5"

[[mgr.prepend_keymap]]
on   = "<C-b>"
run  = "seek -5"

[[mgr.prepend_keymap]]
on   = "+"
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"

[[mgr.prepend_keymap]]
on = "<C-o>"
run = "shell -- dwag %s"
for = "windows"
desc = "Drag files/folders"

[[mgr.prepend_keymap]]
on = [ "m", "c" ]
run = "linemode size_mtime"
desc = "Linemode: size+mtime"

[[mgr.prepend_keymap]]
on   = [ ",", "m" ]
run  = "sort mtime --reverse=no"
desc = "Sort by modified time"

[[mgr.prepend_keymap]]
on   = [ ",", "M" ]
run  = "sort mtime --reverse=yes"
desc = "Sort by modified time (reverse)"

[[mgr.prepend_keymap]]
on   = [ ",", "b" ]
run  = "sort btime --reverse=no"
desc = "Sort by birth time"

[[mgr.prepend_keymap]]
on   = [ ",", "B" ]
run  = "sort btime --reverse=yes"
desc = "Sort by birth time (reverse)"

[[mgr.prepend_keymap]]
on   = [ ",", "s" ]
run  = "sort size --reverse=no"
desc = "Sort by size"

[[mgr.prepend_keymap]]
on   = [ ",", "S" ]
run  = "sort size --reverse=yes"
desc = "Sort by size (reverse)"
