[icon]
dirs  = [
	{ name = ".config", text = "" },
	{ name = ".git", text = "" },
	{ name = ".github", text = "" },
	{ name = ".npm", text = "" },
	{ name = "Desktop", text = "" },
	{ name = "Development", text = "" },
	{ name = "Documents", text = "" },
	{ name = "Downloads", text = "" },
	{ name = "Library", text = "" },
	{ name = "Movies", text = "" },
	{ name = "Music", text = "" },
	{ name = "Pictures", text = "" },
	{ name = "Public", text = "" },
	{ name = "Videos", text = "" },
	{ name = "python", text = "" },
]
