[mgr]
  linemode = "size"

[preview]
  wrap = "yes"
  sort_by = "natural"

[input]
cursor_blink = true

[opener]
edit = [
  { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
  { run = 'neovide %*',    orphan = true, desc = "neovide",           for = "windows" },
  { run = 'nvim -w %*', block = true,  desc = "nvim (block)",   for = "windows" },
  { run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
]

[plugin]
prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },
]
