#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[revset-aliases]
"trunk()" = "main@origin"

[snapshot]
max-new-file-size = 3021365

[fix.tools.1-ruff-lint]
command = ["ruff", "check", "--fix", "--quiet", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.py'"]

[fix.tools.2-ruff-format]
command = ["ruff", "format", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.py'"]
