[preview]
  show_at_start = true
  width_percentage = 50.0
  width_increment_percentage = 5.0
  revision_command = [
    "util",
    "exec",
    "--",
    "d:/Git/Git/bin/bash.exe",
    "-c",
    "jj show $change_id --no-pager --stat --git --color=always | delta --paging=never",
  ]
  oplog_command = ["op", "show", "$operation_id", "--color", "always"]
  file_command = ["diff", "--color", "always", "-r", "$change_id", "$file"]
