#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[revset-aliases]
"trunk()" = "main@origin"

[fix.tools.ruff-lint]
command = ["ruff", "check", "--fix", "--quiet", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.py'"]
line-range-arg = "--lines=$first:$last"

[fix.tools.ruff-format]
command = ["ruff", "format", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.py'"]
line-range-arg = "--lines=$first:$last"
